version: '3'

services: 
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
        - "27017:27017"
  api:
    build: server
    restart: always
    ports:
        - "3000:3000"
    links: 
        - db:db
  nginx:
    build: client
    restart: always
    ports:
      - 8080:80
